export { ReactComponent as ChevronRightIcon } from "assets/svg/icons/chevron-right_icon.svg"
export { ReactComponent as ChevronLeftIcon } from "assets/svg/icons/chevron-left_icon.svg"
export { ReactComponent as PlusCircleIcon } from "assets/svg/icons/plus-circle_icon.svg"
export { ReactComponent as SlidersIcon } from "assets/svg/icons/sliders_icon.svg"
export { ReactComponent as AngleIcon } from "assets/svg/icons/angle_icon.svg"
export { ReactComponent as ResetIcon } from "assets/svg/icons/reset_icon.svg"
export { ReactComponent as CodeIcon } from "assets/svg/icons/code_icon.svg"
